### PR TITLE
Caroline cultivate plants

### PR DESCRIPTION
**Pull request by CarolineMadison**
Made comments for cultivate_plants in index.py and created cultivate_plants.py in actions folder to hold that code.

### CODE REVIEW

**Review by sampita — APPROVED** [review]
🤘

**Review by christianpippin98 — APPROVED** [review]
Looks Good

**Review by CPJackson777 — APPROVED** [review]
tested successfully

**Review by Belljeremiah — APPROVED** [review]
Wonderful! I found your comments easily and I like the Bold text.

**Pull request merged**
