### PR TITLE
Caroline cultivate plants two

### PR DESCRIPTION
**Pull request by CarolineMadison**
# Pull Request

## Instructions
1. Commit your changes to your branch
1. `git fetch --all`
1. `git checkout [branch_name]`

### ... and don't forget to check if code runs:
In your terminal, run `python index.py`

### CODE REVIEW

**Review by sampita — APPROVED** [review]
Looks good and the code still runs 👻

**Review by christianpippin98 — APPROVED** [review]
Looks good

**Review by CPJackson777 — APPROVED** [review]
Tested successfully

**Review by Belljeremiah — APPROVED** [review]
Menu Looks great!

**Pull request merged**
