### PR TITLE
added notes for Arboretum Report

### PR DESCRIPTION
**Pull request by sampita**
What to review:
Check to see that notes are visible in `actions/report.py` followed by my initials

To review code:
- `git fetch --all`
- `git checkout sp-show-arboretum-report`

### CODE REVIEW

**Review by CPJackson777 — APPROVED** [review]
tested successfully. Saw all Sam's comments

**Review by christianpippin98 — APPROVED** [review]
Checked it out, it looks great!

**Review by Belljeremiah — APPROVED** [review]
Looks good great work in a short time! index.py still runs and your comments were good!

**Review by CarolineMadison — APPROVED** [review]
Looks great!

**Pull request merged**
