### PR TITLE
Caroline forest

### PR DESCRIPTION
**Pull request by CarolineMadison**
# Pull Request

## Instructions
1. Commit your changes to your branch
1. `git fetch --all`
1. `git checkout [branch_name]`

### ... and don't forget to check if code runs:
In your terminal, run `python index.py`

### CODE REVIEW

**Review by Belljeremiah — APPROVED** [review]
Looks great after the merge conflics were removed!

**Review by sampita — APPROVED** [review]
Looks good!

**Review by christianpippin98 — APPROVED** [review]
lookin good

**Review by CPJackson777 — APPROVED** [review]
tested successfully

**Pull request merged**
